/**
 * Environment variables
 */
const env = {
	publicEnv: {
		ENVIRONMENT: process.env.NEXT_PUBLIC_ENVIRONMENT,
		FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
		FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
		FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
		FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
		FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
		FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
		FIREBASE_MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
		FIREBASE_FUNCTION_URL: process.env.NEXT_PUBLIC_FIREBASE_FUNCTION_URL,
		STRIPE_SECRET_KEY_PROD: process.env.NEXT_PUBLIC_STRIPE_KEY,
		SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
		SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
	},

	privateEnv: {
		FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
		FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
		FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
		SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
	}
} as const;

export default env;